learing_log/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learningng_logs.urls', namespace='learning_logs')),
]

learningng_logs/urls.py
from django.conf.urls import url


from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^topics/$', views.topics, name='topics'),
    url(r'^topic/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login


from . import views


urlpatterns = [
    #página de login usando view default,passamos um dicionário com o template
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register')
]

learningng_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    """Representa um assunto"""
    text = models.CharField(max_length=200)
    data_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)


    def __str__(self):
        """Imprimte uma string para representar o objeto"""
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'entries'


    def __str__(self):
        """Uma representaçÃo em string do obj"""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learningng_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}



class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text':forms.Textarea(attrs={'cols': 80})}

learningng_logs/views.py
from django.shortcuts import render
from django.utils import log
from .models import Topic, Entry
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .forms import TopicForm, EntryForm


# Create your views here.

def index(request):
    return render(request, 'learning_logs/index.html')



@login_required
def topics(request):
    topics = Topic.objects.filter(owner = request.user).order_by('data_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)



@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)



@login_required
def new_topic(request):
    """Adciona um novo assunto"""
    if request.method != 'POST':
        #Nenhum dado submetido, criar formlário em branco
        form = TopicForm()
        context = {'form': form}
        return render(request, 'learning_logs/new_topic.html', context)
    else:
        #Dados de POST submetidos; processa os dados
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    """
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)
    """



@login_required
def new_entry(request, topic_id):
    """Adciona uma nova entrada sobre assunto"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        #Formulário vázio
        form = EntryForm()
    else:
        #Processa os dados recebidos via POST
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form }
    return render(request, 'learning_logs/new_entry.html', context)



@login_required
def edit_entry(request, entry_id):
    """Editada uma entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'form': form, 'entry': entry, 'topic': topic}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))



def register(request):
    """Faz o cadastro de um novo usuário"""
    if request.method != 'POST':
        #Exibe formulário em branco
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learningng_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning log</a>-
    <a href="{% url 'learning_logs:topics'%}">Topics</a>-
    {% if user.is_authenticated %}
        Hello, {{ user.useranme }}
        <a href="{% url 'users:logout' %}">Log out</a>-
    {% endif%}
        <a href="{% url 'users:login' %}">Log in</a>-
        <a href="{% url 'users:register' %}">Register</a>
</p>
{%block content%}{% endblock %}

learningng_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}


{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> </p>


    <p>Edit entry:</p>


    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">save</button>
    </form>


{% endblock content %}

learningng_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}


{% block content %}
<p>
    Bem-vindo!
</p>
{% endblock content %}

learningng_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>


    <p>Add new entry:</p>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add entry</button>
    </form>


{% endblock content %}

learningng_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% block content %}
    <p>Add a new topic:</p>


    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add topic</button>
    </form>


{% endblock content %}

learningng_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}


{% block content %}


<p>Topic: {{ topic }}</p>
<p>Entries:</p>
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>
<ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date.added|date:'m, d, Y, H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p> -
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
        </li>
    {% empty %}
        <li>No entries</li>
    {% endfor %}
</ul>


{% endblock content %}

learningng_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}


{% block content %}

<a href="{% url 'learning_logs:new_topic' %}">New topic</a>

<p>Topics</p>
<ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </li>
    {% empty %}
        <li>No topics</li>
    {% endfor %}
</ul>


{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}


{% block content %}

    {% if form.errors %}
        <p>Usuário ou senha inválidos. Tente novamente.</p>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">log in</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    </form>


{% endblock content %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">register</button>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    </form>
{% endblock content %}